dbt_project:
  outputs:
    dev:
      dataset: Staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: EU #TODO - set your location.
      method: service-account
      priority: interactive
      project: ghg-capstone
      threads: 1
      type: bigquery
  target: dev
